### PR TITLE
add parameter x

### LINKED ISSUE #5: Parameter -x

### PR DESCRIPTION
**Pull request by justinmueller05082000**
fixes #5

### CODE REVIEW

**Review by Al2Klimov — CHANGES_REQUESTED** [review]
```bash
go run . -x -e 'a|b' <<EOF
a
b
ab
EOF
```

... doesn't work as expected.

**Review by Al2Klimov — CHANGES_REQUESTED** [review]
* [x] `git reset --soft HEAD~$(git rev-list --count $(git merge-base HEAD master)..HEAD^)`
* [x] `git commit --amend --no-edit`
* [x] `git push -f origin feature/parameter-x-5`

**Review by Al2Klimov — CHANGES_REQUESTED** [review]
Write a test protocol.

**Comment by justinmueller05082000** [comment]
**Test protocol:**

**toGrep.txt:**

```
zebra raccoon cat dolphin doggo
zebra raccoon cat dolphin zebra
zebra raccoon cat dolphin gorilla
zebra raccoon cat dolphin horse
zebra raccoon cat dolphin
```

**Go code:**

**Terminal:** `go run . -x -e 'zebra raccoon cat dolphin' < toGrep.txt`

**Output:**

```
zebra raccoon cat dolphin
```

**Grep command:**

**Terminal:**  `grep -x -e 'zebra raccoon cat dolphin' < toGrep.txt`

**Output:**

```
zebra raccoon cat dolphin
```


**Conclusion:**
Both results are equal except for the colored highlighting in the terminal.

**Review by Al2Klimov — CHANGES_REQUESTED** [review]
Prove that -x actually makes a difference.

**Comment by justinmueller05082000** [comment]
i changed it

**Pull request merged**
